export default {
    info:[
        {
            "id":1,
            "simg":"static/images/1-1.jpg",
            "bimg":"static/images/1-2.jpg",
            "tit":"幸福格色",
            "mes":"处女座古堡"
        },
        {
            "id":2,
            "simg":"static/images/2-1.jpg",
            "bimg":"static/images/2-2.jpg",
            "tit":"上海鸿鹄设计",
            "mes":"175m²工业风"
        },
        {
            "id":3,
            "simg":"static/images/3-1.jpg",
            "bimg":"static/images/3-2.jpg",
            "tit":"上海霞霞设计",
            "mes":"175m²现代风"
        }
    ],
    Index:'',
    houseList:{}
}